mani1_config:
# Publish all joint states -----------------------------------
 joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

# Position Controllers ---------------------------------------
 mani1_joint1_controller:
    type: position_controllers/JointPositionController
    joint:  mani1_joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}
 mani1_joint2_controller:
    type: position_controllers/JointPositionController
    joint:  mani1_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}
 mani1_joint3_controller:
    type: position_controllers/JointPositionController
    joint:  mani1_joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}
 mani1_joint4_controller:
    type: position_controllers/JointPositionController
    joint:  mani1_joint4
    pid: {p: 100.0, i: 0.01, d: 10.0}
 mani1_joint5_controller:
    type: position_controllers/JointPositionController
    joint:  mani1_joint5
    pid: {p: 100.0, i: 0.01, d: 10.0}
 mani1_joint6_controller:
    type: position_controllers/JointPositionController
    joint:  mani1_joint6
    pid: {p: 100.0, i: 0.01, d: 10.0}
 mani1_joint7_controller:
    type: position_controllers/JointPositionController
    joint:  mani1_joint7
    pid: {p: 100.0, i: 0.01, d: 10.0}

 mani2_joint1_controller:
    type: position_controllers/JointPositionController
    joint:  mani2_joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}
 mani2_joint2_controller:
    type: position_controllers/JointPositionController
    joint:  mani2_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}
 mani2_joint3_controller:
    type: position_controllers/JointPositionController
    joint:  mani2_joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}
 mani2_joint4_controller:
    type: position_controllers/JointPositionController
    joint:  mani2_joint4
    pid: {p: 100.0, i: 0.01, d: 10.0}
 mani2_joint5_controller:
    type: position_controllers/JointPositionController
    joint:  mani2_joint5
    pid: {p: 100.0, i: 0.01, d: 10.0}
 mani2_joint6_controller:
    type: position_controllers/JointPositionController
    joint:  mani2_joint6
    pid: {p: 100.0, i: 0.01, d: 10.0}
 mani2_joint7_controller:
    type: position_controllers/JointPositionController
    joint:  mani2_joint7
    pid: {p: 100.0, i: 0.01, d: 10.0}


