mani1_config:
 robotic_arm_controller_ver1:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - mani1_joint1
      - mani1_joint2
      - mani1_joint3
      - mani1_joint4
      - mani1_joint5
      - mani1_joint6
      - mani1_joint7

    gains:
      mani1_joint1: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani1_joint2: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani1_joint3: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani1_joint4: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani1_joint5: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani1_joint6: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani1_joint7: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}

 robotic_arm_controller_ver2:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - mani2_joint1
      - mani2_joint2
      - mani2_joint3
      - mani2_joint4
      - mani2_joint5
      - mani2_joint6
      - mani2_joint7

    gains:
      mani2_joint1: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani2_joint2: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani2_joint3: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani2_joint4: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani2_joint5: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani2_joint6: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani2_joint7: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
