# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_ver1
  joint_model_group_pose: home_ver1
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - mani1_joint1
    - mani1_joint2
    - mani1_joint3
    - mani1_joint4
    - mani1_joint5
    - mani1_joint6
    - mani1_joint7
    - mani2_joint1
    - mani2_joint2
    - mani2_joint3
    - mani2_joint4
    - mani2_joint5
    - mani2_joint6
    - mani2_joint7
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100


controller_list:  
  - name: mani1_config/robotic_arm_controller_ver1
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - mani1_joint1
      - mani1_joint2
      - mani1_joint3
      - mani1_joint4
      - mani1_joint5
      - mani1_joint6
      - mani1_joint7
  - name: mani1_config/robotic_arm_controller_ver2
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - mani2_joint1
      - mani2_joint2
      - mani2_joint3
      - mani2_joint4
      - mani2_joint5
      - mani2_joint6
      - mani2_joint7

robotic_arm_controller_ver1:
  type: position_controllers/JointPositionController
  joints:
    - mani1_joint1
    - mani1_joint2
    - mani1_joint3
    - mani1_joint4
    - mani1_joint5
    - mani1_joint6
    - mani1_joint7
  gains:
    mani1_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    mani1_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    mani1_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    mani1_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    mani1_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    mani1_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    mani1_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
robotic_arm_controller_ver2:
  type: position_controllers/JointPositionController
  joints:
    - mani2_joint1
    - mani2_joint2
    - mani2_joint3
    - mani2_joint4
    - mani2_joint5
    - mani2_joint6
    - mani2_joint7
  gains:
    mani2_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    mani2_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    mani2_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    mani2_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    mani2_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    mani2_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    mani2_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
